global:
  scrape_timeout: 10s
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - rules.yml

scrape_configs:
  - job_name: mcp
    scheme: http
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    file_sd_configs:
      - files:
          - 'mcp.json'

  - job_name: application-nodes
    scheme: http
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    file_sd_configs:
      - files:
          - 'app_nodes.json'