alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]


rule_files:
  - rules.yml

global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s


scrape_configs:
  - job_name: monitoring-control-plane
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    scheme: http
    static_configs:
      - labels:
          application: monitoring-control-plane
          environment: development
        targets:
          - cadvisor:8080
          - node_exporter:9100
          - nginx_exporter:9113
          - nginx_request_exporter:4040
  - job_name: application-worker-nodes
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    scheme: http
    static_configs: []