global:
  scrape_timeout: 10s
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - rules.yml

scrape_configs:
  - job_name: mcp
    scheme: http
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    static_configs:
      - labels:
          application: mcp
          environment: production
        targets:
          - cadvisor:8080
          - node_exporter:9100
          - nginx_exporter:9113
          - nginx_request_exporter:4040

  - job_name: application-nodes
    scheme: http
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        regex: 'rfmesh-.*'
        action: keep
      - source_labels: [ __meta_ec2_tag_MCP_SD ]
        regex: true
        action: keep
      - source_labels: [ __meta_ec2_instance_id ]
        target_label: instance
      - source_labels: [ __meta_ec2_tag_Application ]
        target_label: application
      - source_labels: [ __meta_ec2_tag_Environment ]
        target_label: environment
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
      - region: us-east-1
        port: 8080
      - region: us-east-1
        port: 9113
