version: "3"
networks:
  monitoring:
services:
  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /home/ubuntu/docker_data/promtail:/etc/promtail
    ports:
      - "1514:1514"
    restart: always
    command: |
      -config.expand-env=true
      -config.file=/etc/promtail/promtail-config.yml
    environment:
      - ENV=${ENV}
      - HOSTNAME=${HOSTNAME}
    networks:
      - monitoring
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    pid: "host"
    ports:
      - "9100:9100"
    networks:
      - monitoring
