server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://env-a-manager.***REMOVED***/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: ${HOSTNAME}
          environment: ${ENV}
          __path__: /var/log/nginx/*log
  - job_name: supervisor
    static_configs:
      - targets:
        - localhost
        labels:
          job: supervisor
          host: ${HOSTNAME}
          environment: ${ENV}
          __path__: /var/log/supervisor/*log
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: ${HOSTNAME}
          environment: ${ENV}
          __path__: /var/log/*log
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          host: ${HOSTNAME}
          environment: ${ENV}
          __path__: /var/lib/docker/containers/*/*-json.log
