version: "3"
networks:
  monitoring:
services:
  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - /var/log:/var/lo
      - /var/log/supervisor:/var/log/supervisor:ro
      - /home/ubuntu/docker_data/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "1514:1514"
    restart: always
    command:
      -config.expand-env=true
      -config.file=/etc/promtail/promtail-config.yml
    environment:
      - ENV=${ENV}
      - HOSTNAME=${HOSTNAME}
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    pid: "host"
    ports:
      - "9100:9100"
    networks:
      - monitoring

  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "8008:8080"
    volumes:
      - /home/ubuntu/docker_data/nginx:/etc/nginx/conf.d
      - /home/ubuntu/docker_data/nginx/logs:/var/log/nginx
    networks:
      - monitoring

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx_exporter
    restart: always
    command:
      -nginx.scrape-uri=http://host.docker.internal:8080/stub_status
    ports:
      - "9113:9113"
    networks:
      - monitoring