version: "3.8"

networks:
  spotops_monitoring:

x-logging:
  &default-logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    volumes:
      - spotops-prometheus:/prometheus:rw
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    user: root
    restart: always
    command:
      --web.enable-lifecycle
      --storage.tsdb.retention.time=7d
      --config.file=/etc/prometheus/prometheus.yml
    networks:
      - spotops_monitoring

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - spotops-alertmanager:/data:rw
      - ./alert_manager/alertmanager.yml:/config/alertmanager.yml:ro
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - spotops_monitoring

  loki:
    image: grafana/loki:2.4.0
    container_name: "loki"
    volumes:
      - spotops-loki:/data/loki:rw
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml:ro
    ports:
      - "3100:3100"
    restart: always
    environment:
      - "HOSTNAME=mcp"
      - "ENV=development"
      - "APPLICATION=mcp"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - spotops_monitoring

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    user: root
    volumes:
      - spotops-grafana:/var/lib/grafana:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:rw
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:rw
    environment:
      - "GF_INSTALL_PLUGINS=grafana-worldmap-panel,grafana-polystat-panel,novatec-sdg-panel,macropower-analytics-panel"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - spotops_monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /dev/disk:/dev/disk/:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8082:8080"
    networks:
      - spotops_monitoring

  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "1514:1514"
    restart: always
    command:
      -config.expand-env=true
      -config.file=/etc/promtail/promtail-config.yml
    environment:
      - ENV=production
      - HOSTNAME=master-node
      - APPLICATION=monitoting-control-plane
    networks:
      - spotops_monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    pid: "host"
    ports:
      - "9100:9100"
    networks:
      - spotops_monitoring

  jenkins:
    build:
        context: ./custom_jenkins_image/
        dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - spotops-jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spotops_monitoring

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "8008:8080"
    logging: *default-logging
    volumes:
      - spotops-nginx-logs:/var/log/nginx:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - spotops_monitoring

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx_exporter
    restart: always
    command:
      -nginx.scrape-uri=http://nginx:8080/stub_status
    ports:
      - "9113:9113"
    networks:
      - spotops_monitoring

  nginx_request_exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    container_name: nginx_request_exporter
    restart: always
    command:
      - /mnt/nginxlogs/_data/access.log
    volumes:
      - spotops-nginx-logs:/mnt/nginxlogs:ro
    depends_on:
      - nginx
    ports:
      - "4040:4040"
    networks:
      - spotops_monitoring

volumes:
  spotops-loki:
  spotops-grafana:
  spotops-jenkins:
  spotops-prometheus:
  spotops-nginx-logs:
  spotops-alertmanager: