global:
  resolve_timeout: 1m
  slack_api_url: '***REMOVED***'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#development'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462