alerting:
  alertmanagers:
    - static_configs:
        - targets: null
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 10s
rule_files: null
scrape_configs:
  - job_name: master-metrics
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    scheme: http
    static_configs:
      - labels:
          application: monitoring-control-plane
          environment: development
        targets:
          - cadvisor:8080
          - node_exporter:9100
  - job_name: worker-metrics
    metrics_path: /metrics
    relabel_configs:
      - action: replace
        regex: ([^:]+)(:[0-9]+)?
        replacement: ${1}
        source_labels:
          - __address__
        target_label: instance
    scheme: http
    static_configs: []