alerting:
  alertmanagers:
    - static_configs:
        - targets: null
global:
  evaluation_interval: 30s
  scrape_timeout: 10s
  scrape_interval: 30s
rule_files: null
scrape_configs:
  - job_name: master-node-exporter
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          environment: development
          application: monitoring-control-plane

  - job_name: worker-node-exporter
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 3.237.71.223:9100
        labels:
          environment: development
          application: r-service-lookup-spot

  - job_name: worker-cadvisor
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 3.237.71.223:8080
        labels:
          environment: development
          application: r-service-lookup-spot