version: "3"

networks:
  spotops_monitoring:
    driver: bridge

services:
  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/opt/spotops/agents/promtail:/etc/promtail
    ports:
      - "1514:1514"
    restart: always
    command:
      -config.expand-env=true
      -config.file=/etc/promtail/promtail-config.yml
    environment:
      - HOSTNAME=${HOSTNAME}
    networks:
      - spotops_monitoring
    env_file:
      - promtail.env
    deploy:
      resources:
        limits:
          memory: 30M
    labels:
      org.label-schema.group: "monitoring"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: always
    pid: "host"
    ports:
      - "9100:9100"
    networks:
      - spotops_monitoring
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      resources:
        limits:
          memory: 20M
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /cgroup:/cgroup:ro
      - /var/run:/var/run:ro
      - /dev/disk:/dev/disk/:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - spotops_monitoring
    deploy:
      resources:
        limits:
          memory: 100M
    labels:
      org.label-schema.group: "monitoring"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - /var/opt/spotops/agents/nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/opt/spotops/agents/nginx/nginx_main_config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - spotops_monitoring
    deploy:
      resources:
        limits:
          memory: 30M
    labels:
      org.label-schema.group: "monitoring"

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    container_name: nginx_exporter
    restart: always
    command:
      -nginx.scrape-uri=http://nginx:8081/stub_status
    ports:
      - "9113:9113"
    networks:
      - spotops_monitoring
    deploy:
      resources:
        limits:
          memory: 15M
    labels:
      org.label-schema.group: "monitoring"
